version: "3.8"
services:
  # Our NestJS Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api:/teampify/src/app
      - /teampify/src/app/node_modules
    env_file:
      - ./api/.env
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SYNCHRONIZE=${DB_SYNCHRONIZE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on: 
      - postgres
    ports:
      - 3000:3000

  # Our Angular client (WIP)
  
  # Our Postgres Database for NestJS to connect to
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  # The Postgres Admin tool if we want to run some custom queries and so on against our Database
  pg_admin:
    image: dpage/pgadmin4
    restart: always
    depends_on: 
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/postgresql/data
volumes:
  pgdata:
  pgadmin-data: